### ISSUE TITLE
Support for --gpus-per-node directive for SLURM site

### ISSUE THREAD

**Issue by jjlk** [ecmwf/troika#10]
### Is your feature request related to a problem? Please describe.

The gpus_per_node troika directive is missing it would be nice to have it. Especially for the SLURM site.

### Describe the solution you'd like

Add a directive in site.slurm:
```
    directive_translate = {
        "billing_account": b"--account=%s",
        "cpus_per_task": b"--cpus-per-task=%s",
        "gpus_per_node": b"--gpus-per-node=%s",
```

### Describe alternatives you've considered

Can find a workaround with PRAGMA but we should have support support for gpus, right?

### Organisation

ecmwf

**Comment by oiffrig** [comment]
Can't see why not. Is there any other GPU-related option that you would find useful?

In the meantime, you can add it in your site config:
```yaml
sites:
  # [...]
  gpu-cluster:
    # [...]
    directive_translate:
      gpus_per_node: "--gpus-per-node=%s"
```
